// Re-exports of the types generated from the Rust engine, plus the small
// amount of shape the web app adds on top.
//
// Nothing here is hand-written from the Rust definitions: `src/wasm` is
// generated by wasm-pack on every build, so a change to a core type surfaces
// as a TypeScript error rather than as undefined at runtime.

export type {
  CatWeights,
  Contribution,
  Decay,
  DistanceModel,
  Econ,
  Match,
  Region,
  SinkCat,
  WaterPolicy,
  Weights,
} from "@/wasm/heatmatch_wasm";

/** The regions the data covers, in display order. */
export const REGIONS = ["nyc", "upstate"] as const;

/** Sink categories in the order the UI lists them. */
export const SINK_CATS = [
  "pool",
  "wwtp",
  "greenhouse",
  "hospital",
  "hotel",
  "residential_multifamily",
  "university",
  "brewery",
  "school",
  "office",
] as const;

export const CAT_LABELS: Record<(typeof SINK_CATS)[number], string> = {
  pool: "Pools",
  wwtp: "Wastewater",
  greenhouse: "Greenhouses",
  hospital: "Hospitals",
  hotel: "Hotels",
  residential_multifamily: "Apartments",
  university: "Universities",
  brewery: "Breweries",
  school: "Schools",
  office: "Offices",
};

/** What `manifest.json` records about one published asset. */
export interface AssetEntry {
  file: string;
  count: number;
  hash: string;
}

export interface SourceEntry {
  id: string;
  url: string;
  license: string;
  note?: string;
}

export interface Manifest {
  built_at: string;
  datacenters: AssetEntry;
  sinks: AssetEntry;
  water?: AssetEntry;
  zones?: AssetEntry;
  sources: SourceEntry[];
}
