// Re-exports of the types generated from the Rust engine, plus the small
// amount of shape the web app adds on top.
//
// Nothing here is hand-written from the Rust definitions: `src/wasm` is
// generated by wasm-pack on every build, so a change to a core type surfaces
// as a TypeScript error rather than as undefined at runtime.

export type {
  CatWeights,
  Contribution,
  Counterfactual,
  Decay,
  DistanceModel,
  Econ,
  Match,
  MwConfidence,
  Region,
  SinkCat,
  WaterPolicy,
  Weights,
} from "@/wasm/heatmatch_wasm";

// Imported as well as re-exported: the label table below needs it in scope.
import type { Counterfactual, MwConfidence, Region } from "@/wasm/heatmatch_wasm";

/** The regions the data covers, in display order. */
export const REGIONS = ["nyc", "upstate", "nova"] as const;

/** The ranking and map can show one region or all of them at once. */
export type RegionView = Region | "all";
export const REGION_VIEWS = ["all", ...REGIONS] as const;

/** Display names, in one place: three components used to branch on "nyc". */
export const REGION_LABELS: Record<Region, string> = {
  nyc: "New York City",
  upstate: "Upstate",
  nova: "N. Virginia",
};

export const REGION_VIEW_LABELS: Record<RegionView, string> = {
  all: "All",
  ...REGION_LABELS,
};

/** Short forms, for the toggle where four labels must share one row. */
/** How a capacity figure reads at a glance, matching the map's markers:
 *  a solid disc is a stated capacity, an outline is a guess from a footprint. */
export const CONFIDENCE_MARKS: Record<MwConfidence, string> = {
  reported: "\u25cf",
  filed: "\u25cf",
  parcel_estimate: "\u25d0",
  footprint_estimate: "\u25cb",
};

export const CONFIDENCE_LABELS: Record<MwConfidence, string> = {
  reported: "Capacity reported by the operator",
  filed: "Capacity stated in a county approval or utility filing",
  parcel_estimate: "Capacity estimated from assessed building area",
  footprint_estimate: "Capacity estimated from building footprint",
};

/** What a sink heats with today — and so what a connection would displace.
 *  Short, because it sits on every row of the detail table. */
export const COUNTERFACTUAL_LABELS: Record<Counterfactual, string> = {
  gas: "displaces gas",
  electric_resistance: "displaces electric heat",
  heat_pump: "displaces a heat pump",
};

/** How a sink's annual demand was arrived at. Worth showing next to every
 *  number it produced: in Virginia none of them are measured. */
export const DEMAND_SOURCE_LABELS: Record<string, string> = {
  ll84_fuel: "metered",
  comstock_modeled: "modelled",
  footprint_estimate: "from footprint",
  category_default: "assumed",
};

export const REGION_SHORT_LABELS: Record<RegionView, string> = {
  all: "All",
  nyc: "NYC",
  upstate: "Upstate",
  nova: "N. Va.",
};

/** Sink categories in the order the UI lists them. */
export const SINK_CATS = [
  "pool",
  "wwtp",
  "greenhouse",
  "hospital",
  "hotel",
  "residential_multifamily",
  "university",
  "brewery",
  "school",
  "office",
] as const;

export const CAT_LABELS: Record<(typeof SINK_CATS)[number], string> = {
  pool: "Pools",
  wwtp: "Wastewater",
  greenhouse: "Greenhouses",
  hospital: "Hospitals",
  hotel: "Hotels",
  residential_multifamily: "Apartments",
  university: "Universities",
  brewery: "Breweries",
  school: "Schools",
  office: "Offices",
};

/** What `manifest.json` records about one published asset. */
export interface AssetEntry {
  file: string;
  count: number;
  hash: string;
}

export interface SourceEntry {
  id: string;
  url: string;
  license: string;
  note?: string;
}

export interface Manifest {
  built_at: string;
  datacenters: AssetEntry;
  sinks: AssetEntry;
  water?: AssetEntry;
  zones?: AssetEntry;
  /** Per-region seasonal shapes; absent when every region uses the built-ins. */
  profiles?: AssetEntry;
  sources: SourceEntry[];
}
