// Re-exports of the types generated from the Rust engine, plus the small
// amount of shape the web app adds on top.
//
// Nothing here is hand-written from the Rust definitions: `src/wasm` is
// generated by wasm-pack on every build, so a change to a core type surfaces
// as a TypeScript error rather than as undefined at runtime.

export type {
  CatWeights,
  Contribution,
  Counterfactual,
  Decay,
  DistanceModel,
  Econ,
  Match,
  MwConfidence,
  Region,
  SinkCat,
  WaterPolicy,
  Weights,
} from "@/wasm/heatmatch_wasm";

import type { Counterfactual, Match, MwConfidence, Region, SinkCat } from "@/wasm/heatmatch_wasm";

/** The regions the data covers, in display order. */
export const REGIONS = ["nyc", "upstate", "nova", "seattle", "pdx", "svy", "la", "sac"] as const;

export type ByRegion<T> = Record<Region, T>;
/** An untyped object, for the leaf-by-leaf diff and merge of weights. */
export type Plain = Record<string, unknown>;

/** Best first: score descending, id ascending on ties — the engine's own order. */
export const byScore = (a: Match, b: Match) => b.score - a.score || a.dc.localeCompare(b.dc);

/** A point feature collection as ingest writes it. */
export interface PointCollection<P> {
  features: { properties: P; geometry: { coordinates: [number, number] } }[];
}

export interface DcFeature {
  id: string;
  name: string;
  mw: number;
  cooling: string;
  region: Region;
  mw_confidence?: MwConfidence;
  campus_id?: string | null;
}

export interface SinkFeature {
  id: string;
  name: string;
  cat: SinkCat;
  demand_kwh: number;
  demand_source?: string;
  area_m2?: number | null;
}

/** Which state each region is in. The region control groups by this, and a
 *  state view can filter the merged ranking without another schema change. */
export const STATE_OF_REGION: Record<Region, string> = {
  nyc: "NY",
  upstate: "NY",
  nova: "VA",
  seattle: "WA",
  pdx: "OR",
  svy: "CA",
  la: "CA",
  sac: "CA",
};

export const STATE_LABELS: Record<string, string> = {
  NY: "New York",
  VA: "Virginia",
  WA: "Washington",
  OR: "Oregon",
  CA: "California",
};

/** The ranking and map can show one region or all of them at once. */
export type RegionView = Region | "all";

/** Display names, in one place: three components used to branch on "nyc". */
export const REGION_LABELS: Record<Region, string> = {
  nyc: "New York City",
  upstate: "Upstate",
  nova: "N. Virginia",
  seattle: "Seattle",
  pdx: "Portland",
  svy: "Silicon Valley",
  la: "Los Angeles",
  sac: "Sacramento",
};

export const REGION_VIEW_LABELS: Record<RegionView, string> = {
  all: "All",
  ...REGION_LABELS,
};

/** How a capacity figure reads at a glance, matching the map's markers:
 *  a solid disc is a stated capacity, an outline is a guess from a footprint. */
export const CONFIDENCE_MARKS: Record<MwConfidence, string> = {
  reported: "\u25cf",
  filed: "\u25cf",
  parcel_estimate: "\u25d0",
  footprint_estimate: "\u25cb",
};

export const CONFIDENCE_LABELS: Record<MwConfidence, string> = {
  reported: "Capacity reported by the operator",
  filed: "Capacity stated in a county approval or utility filing",
  parcel_estimate: "Capacity estimated from assessed building area",
  footprint_estimate: "Capacity estimated from building footprint",
};

/** What a sink heats with today — and so what a connection would displace.
 *  Short, because it sits on every row of the detail table. */
export const COUNTERFACTUAL_LABELS: Record<Counterfactual, string> = {
  gas: "displaces gas",
  electric_resistance: "displaces electric heat",
  heat_pump: "displaces a heat pump",
};

/** Which region draws a district-heating territory, and what to call it.
 *  Absent means the region has none to draw. */
export const ZONE_LABELS: Partial<Record<Region, string>> = {
  nyc: "Con Ed steam territory",
  seattle: "Enwave steam territory",
};

/** How a sink's annual demand was arrived at. Worth showing next to every
 *  number it produced: in Virginia none of them are measured. */
export const DEMAND_SOURCE_LABELS: Record<string, string> = {
  ll84_fuel: "metered",
  seattle_bench: "metered",
  ab802: "metered",
  comstock_modeled: "modelled",
  footprint_estimate: "from footprint",
  category_default: "assumed",
};

/** Sink categories in the order the UI lists them. */
export const SINK_CATS = [
  "pool",
  "wwtp",
  "greenhouse",
  "hospital",
  "hotel",
  "residential_multifamily",
  "university",
  "brewery",
  "school",
  "office",
] as const;

export const CAT_LABELS: Record<(typeof SINK_CATS)[number], string> = {
  pool: "Pools",
  wwtp: "Wastewater",
  greenhouse: "Greenhouses",
  hospital: "Hospitals",
  hotel: "Hotels",
  residential_multifamily: "Apartments",
  university: "Universities",
  brewery: "Breweries",
  school: "Schools",
  office: "Offices",
};

/** What `manifest.json` records about one published asset. */
interface AssetEntry {
  file: string;
  count: number;
  hash: string;
}

interface SourceEntry {
  id: string;
  url: string;
  license: string;
  note?: string;
  /** Present on sources that were checked and deliberately not used. */
  status?: "not_used" | "not_used_unverified";
}

export interface Manifest {
  built_at: string;
  datacenters: AssetEntry;
  sinks: AssetEntry;
  water?: AssetEntry;
  zones?: AssetEntry;
  /** Per-region seasonal shapes; absent when every region uses the built-ins. */
  profiles?: AssetEntry;
  sources: SourceEntry[];
}
