import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // next-env.d.ts is generated by Next on every build; src/wasm by wasm-pack.
  { ignores: ["out/**", ".next/**", "src/wasm/**", "next-env.d.ts"] },
];

export default config;
